title: Srv-Analy Status
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://srv-analy.fr/
params:
  disableDarkMode: false
  shortDateFormat: 15:04 ‚Äî Jan 2
  down: "#e60000"
  systems:
    - name: Analy.fr
      category: Uncategorized
    - name: Mail.Analy.fr
      category: Uncategorized
    - name: "EDS - API "
      description: ""
      category: Serveurs APIs
    - name: AHExpertises.fr
      description: ""
      category: Sites Vitrine
    - name: MonEspace - AHExpertises.fr
      category: Applications Web
    - name: CG Immo - ChateauDeFeissons.fr
      category: Sites Vitrine
    - name: Brun-Invest.net
      category: Sites Vitrine
    - name: MetsDelys.com
      category: Sites Vitrine
  dateFormat: 02 Jan 06 15:04 MST
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/analy_web_white_10241.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: üìà Monitoring
      link: https://stats.uptimerobot.com/4G0vVFJKoG
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
    - name: Serveurs de Sauvegarde
      description: Les serveurs de sauvegarde principaux sont situ√©s ici.
      closed: true
    - name: Sites Vitrine
      closed: false
      description: Les sites vitrine principaux sont situ√©s ici.
    - description: Les Applis principales sont situ√©es ici.
      name: Applications Web
    - name: Serveurs APIs
      description: Les Serveurs APIs principaux sont situ√©es ici.
      untitled: false
  description: Nous surveillons en permanence l'√©tat de nos services et, en cas
    d'interruption, une note sera publi√©e ici.
  enableCustomHTML: true
  useLargeHeaderDesign: true
theme: analy
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
