title: Srv-Analy Status
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://srv-analy.fr/
params:
  disableDarkMode: true
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: East Coast
    - name: API
      description: Les rouages de l'application.
      category: Uncategorized
    - name: Media Proxy
      description: Il s'agit du service responsable de la diffusion des images, du son
        et de la vidéo. Il dépend de notre CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: https://analy.fr/assets/images/logo_footer.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Serveurs Principaux
      description: Les serveurs principaux sont situés ici.
      closed: true
    - name: East Coast
    - name: Uncategorized
      untitled: true
  description: Nous surveillons en permanence l'état de nos services et, en cas
    d'interruption, une note sera publiée ici.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: analy
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
