title: Srv-Analy Status
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://srv-analy.fr/
params:
  disableDarkMode: false
  shortDateFormat: 15:04 â€” Jan 2
  down: "#e60000"
  systems:
    - name: Analy.fr
      category: Serveurs Analy
    - name: Backup Gateway
      category: Serveurs Analy
    - name: API WebMail
      description: ""
      category: Serveurs Analy
    - name: Media Proxy
      description: Il s'agit du service responsable de la diffusion des images, du son
        et de la vidÃ©o dÃ©pendent de notre CDN.
      category: Uncategorized
  dateFormat: 02 Jan 06 15:04 MST
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/analy_web_white_10241.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: ðŸ“ˆ Monitoring
      link: https://stats.uptimerobot.com/4G0vVFJKoG
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Serveurs Analy
      description: Les serveurs principaux sont situÃ©s ici.
      closed: true
    - name: Serveurs Clients
      closed: false
    - name: Uncategorized
      untitled: true
  description: Nous surveillons en permanence l'Ã©tat de nos services et, en cas
    d'interruption, une note sera publiÃ©e ici.
  enableCustomHTML: true
  useLargeHeaderDesign: true
theme: analy
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
